[versions]
kotlin = "1.9.23"
kotlinx = "1.7.3"

pv = "2.1.3-SNAPSHOT"

pv-gradle-plugin = "1.0.2-SNAPSHOT"

[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx" }
kotlinx-coroutines-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "kotlinx" }

# pv-server = { module = "su.plo.voice.api:server", version.ref = "pv" }
pv-proxy = { module = "su.plo.voice.api:proxy", version.ref = "pv" }

[plugins]
pv-entrypoints = { id = "su.plo.voice.plugin.entrypoints", version.ref = "pv-gradle-plugin" }
pv-kotlin-relocate = { id = "su.plo.voice.plugin.relocate-kotlin", version.ref = "pv-gradle-plugin" }
pv-java-templates = { id = "su.plo.voice.plugin.java-templates", version.ref = "pv-gradle-plugin" }
